### ISSUE TITLE
What's the password to the SSID'S

### ISSUE THREAD

**Issue by nekef** [Tnze/esp32_beaconSpam#5]
This is not really a issue but I was just wondering what the password is to the networks are.
Please reply soon. (-‿◦☀)

**Comment by Tnze** [comment]
Technically no password here. Because we are just sending beacons, and no actual network is created.

**Comment by nekef** [comment]
Thanks.(-‿◦☀)

**Comment by nekef** [comment]
Yes, but because, like, the networks are secure, and I'm wondering what they are. If you don't know, then I won't bother you again unless...

**Comment by Tnze** [comment]
They are fake. So it can tell you whatever there is password or not.

You can modify the code, making it displayed to be opened.

**Comment by nekef** [comment]
thanks
